### PR TITLE
Added support for Maya 2020

### PR DESCRIPTION
**Pull request by mlveggo**
Added support for Maya 2020.

The attached zip file contains Maya LiveLink plugin binaries for 2016-2020.

[MayaLiveLink.zip](https://github.com/ue4plugins/MayaLiveLink/files/4862489/MayaLiveLink.zip)

### CODE REVIEW

**Comment by v769123** [comment]
安装了还灭有使用

**Comment by JimHati** [comment]
Thank you for providing this. When I load the plugin maya only loads the .py not .mll file. I have tried in maya 2019 and 2020 both have the same issue. I am using a mac. Any ideas? Thnaks

**Comment by kyledavidashley** [comment]
yes Thanks very much , you  RUUULE!  the Cyberness (excited/grateful/caffeine)

**Comment by petersmilefly** [comment]
thank you！！！！！！

**Comment by Fire39** [comment]
@mlveggo 
Is it possible to get build for Maya 2022?

**Comment by mattyjams** [comment]
Support for building the plugin for Maya 2020 and Maya 2022 is now available. Maya 2020 support was added in c2e2ef7fe5b0b734b8dee6e0d1dab41499cf52d0, and Maya 2022 support was added in 085f0bb7612183094e04dd140756b0149b1ff365.

Thanks for contributing!

**Pull request closed without merging**
